flowapp/models/log.py
from datetime import datetime, timedelta

from flowapp.constants import RuleTypes
from .base import db


class Log(db.Model):
    """Log model for system actions"""

    id = db.Column(db.Integer, primary_key=True)
    time = db.Column(db.DateTime)
    task = db.Column(db.String(1000))
    author = db.Column(db.String(1000))
    rule_type = db.Column(db.Integer)
    rule_id = db.Column(db.Integer)
    user_id = db.Column(db.Integer)

    def __init__(self, time, task, user_id, rule_type, rule_id, author):
        self.time = time
        self.task = task
        self.rule_type = rule_type
        self.rule_id = rule_id
        self.user_id = user_id
        self.author = author

    @classmethod
    def delete_old(cls, days: int = 30):
        """Delete logs older than :param days from the database"""
        cls.query.filter(cls.time < datetime.now() - timedelta(days=days)).delete()
        db.session.commit()

    def __repr__(self):
        return f"<Log {self.id}>"

    def __str__(self):
        """
        {"author": "vrany@cesnet.cz / Cel\u00fd sv\u011bt", "source": "UI", "command": "cmd"}
        """
        return f"{self.author} - {RuleTypes(self.rule_type).name}({self.rule_id}) - {self.task}"

flowapp/forms/user.py
"""
User-related forms for the flowapp application.
"""

import csv
from io import StringIO

from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectMultipleField
from wtforms.validators import ValidationError, DataRequired, Email, InputRequired, Optional


class UserForm(FlaskForm):
    """
    User Form object
    used in Admin
    """

    uuid = StringField(
        "Unique User ID",
        validators=[
            InputRequired("Please provide UUID"),
            Email("Please provide valid email"),
        ],
    )

    email = StringField("Email", validators=[Optional(), Email("Please provide valid email")])

    comment = StringField("Notice", validators=[Optional()])

    name = StringField("Name", validators=[Optional()])

    phone = StringField("Contact phone", validators=[Optional()])

    role_ids = SelectMultipleField("Role", coerce=int, validators=[DataRequired("Select at last one role")])

    org_ids = SelectMultipleField(
        "Organization",
        coerce=int,
        validators=[DataRequired("We prefer one Organization per user, but it's possible select more")],
    )


class BulkUserForm(FlaskForm):
    """
    Bulk User Form object
    used in Admin
    """

    users = TextAreaField("Users in CSV - see example below", validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        super(BulkUserForm, self).__init__(*args, **kwargs)
        self.roles = None
        self.organizations = None
        self.uuids = None

    # Custom validator for CSV data
    def validate_users(self, field):
        csv_data = field.data

        # Parse CSV data
        csv_reader = csv.DictReader(StringIO(csv_data), delimiter=",")

        # List to keep track of failed validation rows
        errors = 0
        for row_num, row in enumerate(csv_reader, start=1):
            try:
                # check if the user not already exists
                if row["uuid-eppn"] in self.uuids:
                    field.errors.append(f"Row {row_num}: User with UUID {row['uuid-eppn']} already exists.")
                    errors += 1

                # Check if role exists in the database
                role_id = int(row["role"])  # Convert role field to integer
                if role_id not in self.roles:
                    field.errors.append(f"Row {row_num}: Role ID {role_id} does not exist.")
                    errors += 1

                # Check if organization exists in the database
                org_id = int(row["organizace"])  # Convert organization field to integer
                if org_id not in self.organizations:
                    field.errors.append(f"Row {row_num}: Organization ID {org_id} does not exist.")
                    errors += 1

            except (KeyError, ValueError) as e:
                field.errors.append(f"Row {row_num}: Invalid data / key - {str(e)}. Check CSV head row.")

        if errors > 0:
            # Raise validation error if any invalid rows found
            raise ValidationError("Invalid CSV Data - check the errors above.")

flowapp/views/api_keys.py
import jwt
from flask import (
    Blueprint,
    render_template,
    redirect,
    flash,
    request,
    url_for,
    session,
    make_response,
    current_app,
)
import secrets

from ..forms import ApiKeyForm
from ..models import ApiKey
from ..auth import auth_required

from flowapp import db

COOKIE_KEY = "keylist"

api_keys = Blueprint("api_keys", __name__, template_folder="templates")


@api_keys.route("/", methods=["GET"])
@auth_required
def all():
    """
    Show user api keys
    :return: page with keys
    """
    jwt_key = current_app.config.get("JWT_SECRET")
    keys = db.session.query(ApiKey).filter_by(user_id=session["user_id"]).all()
    payload = {"keys": [key.id for key in keys]}
    encoded = jwt.encode(payload, jwt_key, algorithm="HS256")

    resp = make_response(render_template("pages/api_key.html", keys=keys))

    if current_app.config.get("DEVEL"):
        resp.set_cookie(COOKIE_KEY, encoded, httponly=True, samesite="Lax")
    else:
        resp.set_cookie(COOKIE_KEY, encoded, secure=True, httponly=True, samesite="Lax")

    return resp


@api_keys.route("/add", methods=["GET", "POST"])
@auth_required
def add():
    """
    Add new ApiKey
    :return: form or redirect to list of keys
    """
    generated = secrets.token_hex(24)
    form = ApiKeyForm(request.form, key=generated)

    if request.method == "POST" and form.validate():
        model = ApiKey(
            machine=form.machine.data,
            key=form.key.data,
            expires=form.expires.data,
            readonly=form.readonly.data,
            comment=form.comment.data,
            user_id=session["user_id"],
            org_id=session["user_org_id"],
        )

        db.session.add(model)
        db.session.commit()
        flash("NewKey saved", "alert-success")

        return redirect(url_for("api_keys.all"))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                current_app.logger.debug("Error in the %s field - %s" % (getattr(form, field).label.text, error))

    return render_template("forms/api_key.html", form=form, generated_key=generated)


@api_keys.route("/delete/<int:key_id>", methods=["GET"])
@auth_required
def delete(key_id):
    """
    Delete api_key and machine
    :param key_id: integer
    """
    key_list = request.cookies.get(COOKIE_KEY)
    key_list = jwt.decode(key_list, current_app.config.get("JWT_SECRET"), algorithms=["HS256"])

    model = db.session.get(ApiKey, key_id)
    if model.id not in key_list["keys"]:
        flash("You can't delete this key!", "alert-danger")
    elif model.user_id == session["user_id"] or 3 in session["user_role_ids"]:
        # delete from db
        db.session.delete(model)
        db.session.commit()
        flash("Key deleted", "alert-success")
    else:
        flash("You can't delete this key!", "alert-danger")

    return redirect(url_for("api_keys.all"))

flowapp/views/dashboard.py
import subprocess
from datetime import datetime
from dataclasses import dataclass

from flask import (
    Blueprint,
    current_app,
    render_template,
    render_template_string,
    request,
    session,
    make_response,
    abort,
    redirect,
    url_for,
)

from markupsafe import Markup
from flowapp import models, validators, flowspec
from flowapp.auth import auth_required
from flowapp.constants import (
    SORT_ARG,
    ORDER_ARG,
    DEFAULT_ORDER,
    DEFAULT_SORT,
    SEARCH_ARG,
    RULE_ARG,
    TYPE_ARG,
    ORDSRC_ARG,
    COMP_FUNCS,
    DEFAULT_COUNT_MATCH,
)
from flowapp.utils import active_css_rstate, other_rtypes

dashboard = Blueprint("dashboard", __name__, template_folder="templates")

# Pagination constants
PAGE_ARG = "page"
PER_PAGE_DEFAULT = 50  # Default number of items per page
PER_PAGE_OPTIONS = [25, 50, 100, 200]  # Options for items per page
PER_PAGE_ARG = "per_page"


@dashboard.route("/whois/<string:ip_address>", methods=["GET"])
@auth_required
def whois(ip_address):
    result = subprocess.run(["whois", ip_address], stdout=subprocess.PIPE)
    return render_template(
        "pages/dashboard_whois.html",
        result=result.stdout.decode("utf-8"),
        ip_address=ip_address,
    )


@dashboard.route("/<path:rtype>/<path:rstate>/")
@auth_required
def index(rtype=None, rstate="active"):
    """
    dispatcher object for the dashboard
    :param rtype:  ipv4, ipv6, rtbh, whitelist
    :param rstate: active, expired, all
    :return: view from view factory
    """

    # set first key of dashboard config as default rtype
    if not rtype:
        rtype = next(iter(current_app.config["DASHBOARD"].keys()))

    # params sanitization
    if rtype not in current_app.config["DASHBOARD"].keys():
        return abort(404)
    if rstate not in COMP_FUNCS.keys():
        return abort(404)
    if sum(session["user_role_ids"]) == 1:
        rstate = "active"

    # select view factory function based on user role
    if 3 in session["user_role_ids"]:
        view_factory = create_admin_response
    elif 2 in session["user_role_ids"]:
        view_factory = create_user_response
    else:
        view_factory = create_view_response

    # get the macros for the current rule type from config
    macro_file = current_app.config["DASHBOARD"].get(rtype).get("macro_file", "macros.html")
    macro_tbody = current_app.config["DASHBOARD"].get(rtype).get("macro_tbody", "build_ip_tbody")
    macro_thead = current_app.config["DASHBOARD"].get(rtype).get("macro_thead", "build_rules_thead")
    macro_tfoot = current_app.config["DASHBOARD"].get(rtype).get("macro_tfoot", "build_group_buttons_tfoot")

    data_handler_module = current_app.config["DASHBOARD"].get(rtype).get("data_handler", models)
    data_handler_method = current_app.config["DASHBOARD"].get(rtype).get("data_handler_method", "get_ip_rules")

    # Get pagination parameters
    page = request.args.get(PAGE_ARG, 1, type=int)
    per_page = request.args.get(PER_PAGE_ARG, PER_PAGE_DEFAULT, type=int)

    # Validate per_page
    if per_page not in PER_PAGE_OPTIONS:
        per_page = PER_PAGE_DEFAULT

    # get search query, sort order and sort key from request or session
    get_search_query = request.args.get(SEARCH_ARG, session.get(SEARCH_ARG, ""))
    get_sort_key = request.args.get(SORT_ARG, session.get(SORT_ARG, DEFAULT_SORT))
    get_sort_order = request.args.get(ORDER_ARG, session.get(ORDER_ARG, DEFAULT_ORDER))
    get_sort_order_source = request.args.get(ORDSRC_ARG, session.get(ORDSRC_ARG, ""))

    # store current state for redirects
    session[ORDER_ARG] = get_sort_order
    session[SORT_ARG] = get_sort_key
    session[RULE_ARG] = rstate
    session[TYPE_ARG] = rtype
    session[SEARCH_ARG] = get_search_query

    # switch order when click on the same column twice
    try:
        if session[SORT_ARG] == get_sort_key and get_sort_order_source == "link":
            get_sort_order = "desc" if get_sort_order == "asc" else "asc"
            session[ORDER_ARG] = get_sort_order
    except KeyError:
        get_sort_order = DEFAULT_ORDER

    # get the handler and the data
    handler = getattr(data_handler_module, data_handler_method)

    # Determine if we're searching
    is_searching = bool(get_search_query)

    # Always fetch ALL rules first (no pagination at DB level when searching)
    if is_searching:
        # Get all rules for search
        rules = handler(rtype, rstate, get_sort_key, get_sort_order, paginate=False)

        # Perform search on all rules
        rules = filter_rules(rules, get_search_query)

        # Now paginate the search results in memory
        pagination = paginate_list(rules, page, per_page)
        # Get the slice of rules for current page
        start_idx = (page - 1) * per_page
        end_idx = start_idx + per_page
        rules = rules[start_idx:end_idx]

        # Get counts for other rule types
        count_match = current_app.config["COUNT_MATCH"]
        count_match[rtype] = pagination.total
        for other_rtype in other_rtypes(rtype):
            other_rules = handler(other_rtype, rstate, get_sort_key, get_sort_order, paginate=False)
            other_rules = filter_rules(other_rules, get_search_query)
            count_match[other_rtype] = len(other_rules)
    else:
        # No search - use normal pagination or fetch all
        use_pagination = rstate in ["expired", "all"]

        if use_pagination:
            # Use paginated version from DB
            rules_data = handler(
                rtype, rstate, get_sort_key, get_sort_order, page=page, per_page=per_page, paginate=True
            )
            if isinstance(rules_data, tuple):
                rules, pagination = rules_data
            else:
                rules = rules_data
                pagination = None
        else:
            # Fetch all rules for 'active' state
            rules = handler(rtype, rstate, get_sort_key, get_sort_order, paginate=False)
            pagination = None

        count_match = ""

    # Enrich rules with whitelist information
    rules, whitelist_rule_ids = enrich_rules_with_whitelist_info(rules, rtype)

    allowed_communities = current_app.config["ALLOWED_COMMUNITIES"]

    return view_factory(
        rtype=rtype,
        rstate=rstate,
        rules=rules,
        sort_key=get_sort_key,
        sort_order=get_sort_order,
        table_colspan=current_app.config["DASHBOARD"][rtype]["table_colspan"],
        table_columns=current_app.config["DASHBOARD"][rtype]["table_columns"],
        table_title=f'{current_app.config["DASHBOARD"][rtype]["name"]} rules',
        search_query=get_search_query,
        count_match=count_match,
        macro_file=macro_file,
        macro_tbody=macro_tbody,
        macro_thead=macro_thead,
        macro_tfoot=macro_tfoot,
        whitelist_rule_ids=whitelist_rule_ids,
        allowed_communities=allowed_communities,
        pagination=pagination,
        per_page=per_page,
        per_page_options=PER_PAGE_OPTIONS,
    )


# Add this route to your dashboard.py Blueprint


@dashboard.route("/clear-search")
@auth_required
def clear_search():
    """
    Clear the search query from session and redirect back to the current view.
    """
    # Get current rtype and rstate before clearing
    rtype = session.get(TYPE_ARG, next(iter(current_app.config["DASHBOARD"].keys())))
    rstate = session.get(RULE_ARG, "active")
    sort_key = session.get(SORT_ARG, DEFAULT_SORT)
    sort_order = session.get(ORDER_ARG, DEFAULT_ORDER)

    # Clear the search query from session
    session[SEARCH_ARG] = ""

    # Redirect back to dashboard with current settings but no search
    return redirect(url_for("dashboard.index", rtype=rtype, rstate=rstate, sort=sort_key, order=sort_order))


# Helper functions


@dataclass
class Pagination:
    page: int
    per_page: int
    total: int
    pages: int
    has_prev: bool
    has_next: bool
    prev_num: int = None
    next_num: int = None
    first: int = 0
    last: int = 0


def paginate_list(items, page, per_page):
    """
    Create a pagination object from a list of items.
    This mimics SQLAlchemy's pagination for in-memory lists.

    :param items: List of items to paginate
    :param page: Current page number (1-indexed)
    :param per_page: Number of items per page
    :return: Pagination-like object
    """
    total = len(items)
    pages = (total + per_page - 1) // per_page  # Ceiling division

    has_prev = page > 1
    has_next = page < pages

    prev_num = page - 1 if has_prev else None
    next_num = page + 1 if has_next else None

    # Calculate first and last item numbers for display
    first = (page - 1) * per_page + 1 if total > 0 else 0
    last = min(page * per_page, total)

    pagination = Pagination(
        page=page,
        per_page=per_page,
        total=total,
        pages=pages,
        has_prev=has_prev,
        has_next=has_next,
        prev_num=prev_num,
        next_num=next_num,
        first=first,
        last=last,
    )

    return pagination


def create_dashboard_table_body(
    rules,
    rtype,
    editable=True,
    group_op=True,
    macro_file="macros.html",
    macro_name="build_ip_tbody",
    whitelist_rule_ids=None,
    allowed_communities=None,
):
    """
    create the table body for the dashboard using a jinja2 macro
    :param rules:  list of rules
    :param rtype:  ipv4, ipv6, rtbh
    :param editable: whether rules can be edited
    :param group_op: whether group operations are allowed
    :param macro_file:  the file where the macro is defined
    :param macro_name:  the name of the macro
    :param whitelist_rule_ids: set of rule IDs that were created by a whitelist
    """
    tstring = "{% "
    tstring = tstring + f"from '{macro_file}' import {macro_name}"
    tstring = tstring + " %} {{"
    tstring = (
        tstring + f" {macro_name}(rules, today, editable, group_op, whitelist_rule_ids, allowed_communities) " + "}}"
    )

flowapp/templates/pages/as_paths.html
{% extends 'layouts/default.html' %}
{% block title %}AS Paths{% endblock %}
{% block content %}
    <table class="table table-hover">
    <tr>
    <th>Prefix</th>
    <th>AS-path</th>
    <th>Action</th>
    </tr>
    {% for pth in paths %}
        <tr>
        <td>{{ pth.prefix }}</td>
        <td>
            {{ pth.as_path }}
        </td>
        <td>
        <a class="btn btn-info btn-sm" href="{{ url_for('admin.edit_as_path', path_id=pth.id) }}" role="button">
            <i class="bi bi-pen"></i>
        </a>
        <form method="POST" action="{{ url_for('admin.delete_as_path', path_id=pth.id) }}" style="display:inline;" onsubmit="return confirm('Are you sure you want to delete this AS path?');">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <button type="submit" class="btn btn-danger btn-sm">
                <i class="bi bi-x-lg"></i>
            </button>
        </form>
        </td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

flowapp/templates/pages/communities.j2
{% extends 'layouts/default.j2' %}
{% block title %}Flowspec RTBH communities{% endblock %}
{% block content %}
    <table class="table table-hover">
    <tr>
    <th>Id</th>
    <th>Display Name</th>
    <th>Community</th>
    <th>Large comm.</th>
    <th>Extended comm.</th>
    <th>AS-path</th>
    <th>Description</th>
    <th>Minimum level</th>
    <th>Edit</th>
    </tr>
    {% for community in communities %}
        <tr>
        <td>{{ community.id }}</td>
        <td>{{ community.name }}</td>
        <td>{{ community.comm }}</td>
        <td>{{ community.larcomm }}</td>
        <td>{{ community.extcomm }}</td>
        <td>{{ community.as_path }}</td>
        <td>
            {{ community.description }}
        </td>
        <td>
            {{ community.role }}
        </td>
        <td>
        <a class="btn btn-info btn-sm" href="{{ url_for('admin.edit_community', community_id=community.id) }}" role="button">
            <i class="bi bi-pen"></i>
        </a>
        <a class="btn btn-danger btn-sm" href="{{ url_for('admin.delete_community', community_id=community.id) }}" role="button">
            <i class="bi bi-x-lg"></i>
        </a>
        </td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

flowapp/templates/pages/dashboard_admin.j2
{% extends 'layouts/default.j2' %}


{% block title %}Flowspec{% endblock %}
{% block content %}

    {% include 'pages/submenu_dashboard.j2' %}
    {% if display_rules %}
    <div class="row">
        <form action="{{ url_for('rules.group_operation') }}" method="post">
         <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <table class="table table-hover ip-table">
            {{ dashboard_table_head }} 
            
            {{ dashboard_table_body }}
            
            {{ dashboard_table_foot }}
        </table>
        </form>
    </div>
    <script type="text/javascript" src="{{ url_for('static', filename='js/check_all.js') }}"></script>
    {% else %}
        <h2>There are no {{ rstate|capitalize }} {{ table_title }}.</h2>
    {% endif %}
{% endblock %}

flowapp/templates/pages/dashboard_search.j2
{% extends 'layouts/default.j2' %}
{% from 'macros.j2' import build_ip_tbody, build_rtbh_tbody, build_rules_thead %}

{% block title %}Flowspec{% endblock %}
{% block content %}
 <div class="content">
    {% include 'pages/submenu_dashboard.j2' %}

    <div class="row">
        <table class="table table-hover ip-table">
            {{ build_rules_thead(rules_columns, rtype, rstate, sort_key, sort_order) }}
            {% if rtype_int == 1 %}
                {{ build_rtbh_tbody(rules, today, rtype_int) }}
            {% else %}
                {{ build_ip_tbody(rules, today, rtype_int) }}
            {% endif %}
        </table>
    </div>
 </div>

{% endblock %}

flowapp/templates/pages/dashboard_search_form.html
{% block dashboard_search_form %}
<form id="dashboard-search" class="navbar-form mx-3" role="search"
    action="{{ url_for('dashboard.index', rtype=rtype, rstate=rstate) }}">
    <div class="input-group">
        <input class="form-control" type="search" name="squery" data-clear-url="{{ url_for('dashboard.clear_search') }}"
            {% if search_query %} value="{{search_query}}" {% else %} placeholder="Search..." {% endif %}>
        <button class="btn btn-outline-secondary" type="submit" title="Search">
            <i class="bi bi-search"></i>
        </button>
        {% if search_query %}
        <a href="{{ url_for('dashboard.clear_search') }}" class="btn btn-outline-danger" title="Clear search">
            <i class="bi bi-x-circle"></i>
        </a>
        {% endif %}
    </div>
    <input type="hidden" name="sort" value="{{ sort_key }}" />
    <input type="hidden" name="order" value="{{ sort_order }}" />
</form>
{% endblock %}

flowapp/templates/pages/dashboard_user.j2
{% extends 'layouts/default.j2' %}
{% from 'macros.j2' import build_ip_tbody, build_rtbh_tbody, build_rules_thead %}


{% block title %}Flowspec{% endblock %}
{% block content %}

    {% include 'pages/submenu_dashboard.j2' %}



    {% if display_editable %}
    <h2>{{ rstate|capitalize }} {{ table_title }} that you can modify</h2>
    <form action="{{ url_for('rules.group_operation') }}" method="post">
         <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <table class="table table-hover ip-table">
        {{ dashboard_table_editable_head }}
        {{ dashboard_table_editable }}
        {{ dashboard_table_foot }}}
        </table>
    </form>
    <script type="text/javascript" src="{{ url_for('static', filename='js/check_all.js') }}"></script>
    {% else %}
        <h2>There are no {{ rstate|capitalize }} {{ table_title }}.</h2>
    {% endif %}

    {% if display_readonly %}
    <h2>{{ rstate|capitalize }}  {{ table_title }} that are read-only for you</h2>
        <p>Those rules somehow including your network ranges. You can see them all for your information. However, you can not modify their expiration time or delete them.</p>
        <table class="table table-hover ip-table">
        {{ dashboard_table_readonly_head }}
        {{ dashboard_table_readonly }}
        </table>
    {% else %}
        <h2>There are no read only {{ rstate }}  {{ table_title }}.</h2>
    {% endif %}

    <script type="text/javascript">
    </script>

{% endblock %}

flowapp/templates/pages/dashboard_whois.html
{% extends 'layouts/default.html' %}

{% block title %}Flowspec{% endblock %}
{% block content %}
    <h2>WHOIS for {{ ip_address }}</h2>

    <div class="row">
        <pre>{{ result }}</pre>        
    </div>

{% endblock %}

flowapp/templates/pages/logout.html
{% extends 'layouts/default.html' %}
{% block title %}Flowspec - logout{% endblock %}
{% block content %}
    <h1>Good Bye</h1>
    <h2>Server time: {{ time }}</h2>
{% endblock %}

flowapp/templates/pages/logs.html
{% extends 'layouts/default.html' %}
{% block title %}Flowspec Users{% endblock %}
{% block content %}
    <h2>Commands log / latest on top</h2>
    {% if logs %}
        <h5>
        {% if logs.has_prev %}<a href="{{ url_for('admin.log', page=logs.prev_num) }}">&lt;&lt; Newer logs</a>{% else %}&lt;&lt; Newer logs{% endif %} | 
        {% if logs.has_next %}<a href="{{ url_for('admin.log', page=logs.next_num) }}">Older logs &gt;&gt;</a>{% else %}Older logs &gt;&gt;{% endif %}
        </h5>
        <table class="table table-hover">
        <tr>
        <th>time</th>
        <th>task</th>
        <th>rule_type</th>
        <th>rule_id</th>
        <th>author</th>
        </tr>
        {% for log in logs.items %}
            <tr>
            <td>{{ log.time|strftime }}</td>
            <td>{{ log.task }}</td>
            <td>{{ log.rule_type }}</td>
            <td>{{ log.rule_id }}</td>
            <td>{{ log.author }}</td>
            </tr>
        {% endfor %}
        </table>
        <h5>
        {% if logs.has_prev %}<a href="{{ url_for('admin.log', page=logs.prev_num) }}">&lt;&lt; Newer logs</a>{% else %}&lt;&lt; Newer logs{% endif %} | 
        {% if logs.has_next %}<a href="{{ url_for('admin.log', page=logs.next_num) }}">Older logs &gt;&gt;</a>{% else %}Older logs &gt;&gt;{% endif %}
        </h5>
    {% else %}
        <h3>No logs for last two days</h3>
    {% endif %}
{% endblock %}

flowapp/templates/pages/submenu_dashboard.html
{% block submenu_dashboard %}
    <div class="container" id="dashboard-nav">
    
    <h1>{{ rstate|capitalize }} {{ table_title }}</h1>
    <div class="row">  
        <div class="col-6">
            <ul class="nav nav-pills">
            {% for key, item in dashboard.items() %}
                <li class="nav-item">
                    <a class="nav-link {{ css_classes[key] }}" href="{{ url_for('dashboard.index', rtype=key, rstate=rstate) }}" >
                    {{ item.name }} 
                    {% if count_match %}
                        ({{ count_match[key] }})
                    {% endif %}
                    </a>
                </li>
            {% endfor %}    
            </ul>
        </div>
        <div class="col-6">
            <ul class="nav nav-pills justify-content-end">
                <li class="nav-item"> 
                    {% include 'pages/dashboard_search_form.html' %}
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ css_classes['active'] }}" href="{{ url_for('dashboard.index', rtype=rtype, rstate='active') }}" >Active</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ css_classes['expired'] }}" href="{{ url_for('dashboard.index', rtype=rtype, rstate='expired') }}" >Expired</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {{ css_classes['all'] }}" href="{{ url_for('dashboard.index', rtype=rtype, rstate='all') }}" >All</a>
                </li>
            </ul>
        </div>
    </div>
    
    {% if search_query %}
    <div class="row mt-2">
        <div class="col-12">
            <div class="alert alert-info alert-dismissible fade show py-2" role="alert">
                <small>
                    <i class="bi bi-search"></i> Searching for: <strong>{{ search_query }}</strong>
                    {% if count_match and count_match[rtype] is defined %}
                        <span class="badge bg-primary ms-2">{{ count_match[rtype] }} results in {{ rtype|upper }}</span>
                        {% for other_type, count in count_match.items() %}
                            {% if other_type != rtype and count > 0 %}
                                <span class="badge bg-secondary ms-1">{{ count }} in {{ other_type|upper }}</span>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </small>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close" data-clear-url="{{ url_for('dashboard.clear_search') }}"></button>
            </div>
        </div>
    </div>
    {% endif %}
    
    <hr />

{% endblock %}