flowapp/views/rules.py
# flowapp/views/admin.py
from datetime import datetime, timedelta
from collections import namedtuple

from flask import Blueprint, current_app, flash, redirect, render_template, request, session, url_for
from flask_wtf.csrf import validate_csrf
from wtforms import ValidationError

from flowapp import constants, db
from flowapp.auth import (
    admin_required,
    auth_required,
    is_admin,
    localhost_only,
    user_or_admin_required,
)
from flowapp.constants import RuleTypes
from flowapp.forms import IPv4Form, IPv6Form, RTBHForm
from flowapp.models import (
    RTBH,
    Action,
    Community,
    Flowspec4,
    Flowspec6,
    Organization,
    check_global_rule_limit,
    check_rule_limit,
    get_user_actions,
    get_user_communities,
    get_user_nets,
    insert_initial_communities,
)
from flowapp.models.log import Log
from flowapp.output import ROUTE_MODELS, announce_route, log_route, log_withdraw, RouteSources, Route
from flowapp.services import rule_service, announce_all_routes, delete_expired_whitelists
from flowapp.utils import (
    flash_errors,
    get_state_by_time,
    round_to_ten_minutes,
)
from flowapp.auth import get_user_allowed_rule_ids, check_user_can_modify_rule


rules = Blueprint("rules", __name__, template_folder="templates")

DATA_MODELS = {1: RTBH, 4: Flowspec4, 6: Flowspec6}
DATA_MODELS_NAMED = {"rtbh": RTBH, "ipv4": Flowspec4, "ipv6": Flowspec6}
DATA_FORMS = {1: RTBHForm, 4: IPv4Form, 6: IPv6Form}
DATA_FORMS_NAMED = {"rtbh": RTBHForm, "ipv4": IPv4Form, "ipv6": IPv6Form}
DATA_TEMPLATES = {
    1: "forms/rtbh_rule.html",
    4: "forms/ipv4_rule.html",
    6: "forms/ipv6_rule.html",
}
DATA_TABLES = {1: "RTBH", 4: "flowspec4", 6: "flowspec6"}
DEFAULT_SORT = {1: "ivp4", 4: "source", 6: "source"}


@rules.route("/reactivate/<int:rule_type>/<int:rule_id>", methods=["GET", "POST"])
@auth_required
@user_or_admin_required
def reactivate_rule(rule_type, rule_id):
    """
    Set new time for the rule of given type identified by id
    :param rule_type: integer - type of rule, corresponds to RuleTypes enum value
    :param rule_id: integer - id of the rule
    """
    # Convert the integer rule_type to RuleTypes enum
    enum_rule_type = RuleTypes(rule_type)

    # Now use the enum value where needed but the integer for dictionary lookups
    model_name = DATA_MODELS[rule_type]
    form_name = DATA_FORMS[rule_type]

    model = db.session.get(model_name, rule_id)
    if not model:
        flash("Rule not found", "alert-danger")
        return redirect(url_for("index"))

    form = form_name(request.form, obj=model)
    form.net_ranges = get_user_nets(session["user_id"])

    if rule_type > 2:
        form.action.choices = [(g.id, g.name) for g in db.session.query(Action).order_by("name")]
        form.action.data = model.action_id

    if rule_type == RuleTypes.RTBH.value:
        form.community.choices = get_user_communities(session["user_role_ids"])
        form.community.data = model.community_id

    if rule_type == RuleTypes.IPv4.value:
        form.protocol.data = model.protocol

    if rule_type == RuleTypes.IPv6.value:
        form.next_header.data = model.next_header

    # Process form submission
    if request.method == "POST":
        # Round expiration time to 10 minutes
        expires = round_to_ten_minutes(form.expires.data)

        # Use the service to reactivate the rule
        _, messages = rule_service.reactivate_rule(
            rule_type=enum_rule_type,
            rule_id=rule_id,
            expires=expires,
            comment=form.comment.data,
            user_id=session["user_id"],
            org_id=session["user_org_id"],
            user_email=session["user_email"],
            org_name=session["user_org"],
        )

        # Handle special messages (redirects)
        if "global_limit_reached" in messages:
            return redirect(url_for("rules.global_limit_reached", rule_type=rule_type))
        if "limit_reached" in messages:
            return redirect(url_for("rules.limit_reached", rule_type=rule_type))

        for message in messages:
            flash(message, "alert-success")

        return redirect(
            url_for(
                "dashboard.index",
                rtype=session[constants.TYPE_ARG],
                rstate=session[constants.RULE_ARG],
                sort=session[constants.SORT_ARG],
                squery=session[constants.SEARCH_ARG],
                order=session[constants.ORDER_ARG],
            )
        )
    else:
        flash_errors(form)

    # For GET requests, prepare the form for display
    form.expires.data = model.expires
    for field in form:
        if field.name not in ["expires", "csrf_token", "comment"]:
            field.render_kw = {"disabled": "disabled"}

    action_url = url_for("rules.reactivate_rule", rule_type=rule_type, rule_id=rule_id)

    return render_template(
        DATA_TEMPLATES[rule_type],
        form=form,
        action_url=action_url,
        editing=True,
        title="Update",
    )


@rules.route("/delete/<int:rule_type>/<int:rule_id>", methods=["GET"])
@auth_required
@user_or_admin_required
def delete_rule(rule_type, rule_id):
    """
    Delete rule with given id and type
    :param rule_type: integer - type of rule to be deleted
    :param rule_id: integer - rule id
    """
    # Validate CSRF token from query parameter
    try:
        validate_csrf(request.args.get("csrf_token", ""))
    except ValidationError:
        flash("CSRF token missing or invalid.", "alert-danger")
        return redirect(url_for("dashboard.index"))

    # Convert the integer rule_type to RuleTypes enum
    enum_rule_type = RuleTypes(rule_type)

    # Get the rule type string for access checking
    rule_type_map = {RuleTypes.IPv4.value: "ipv4", RuleTypes.IPv6.value: "ipv6", RuleTypes.RTBH.value: "rtbh"}
    rule_type_str = rule_type_map.get(rule_type)

    # Check if user can modify this rule
    if not check_user_can_modify_rule(rule_id, rule_type_str):
        flash("You cannot delete this rule", "alert-warning")
        return redirect(
            url_for(
                "dashboard.index",
                rtype=session[constants.TYPE_ARG],
                rstate=session[constants.RULE_ARG],
                sort=session[constants.SORT_ARG],
                squery=session[constants.SEARCH_ARG],
                order=session[constants.ORDER_ARG],
            )
        )

    # Get allowed rule IDs for the service call
    allowed_rule_ids = get_user_allowed_rule_ids(rule_type_str, session["user_id"], session["user_role_ids"])

    # Use the service to delete the rule
    success, message = rule_service.delete_rule(
        rule_type=enum_rule_type,
        rule_id=rule_id,
        user_id=session["user_id"],
        user_email=session["user_email"],
        org_name=session["user_org"],
        allowed_rule_ids=allowed_rule_ids,
    )

    flash(message, "alert-success" if success else "alert-warning")

    return redirect(
        url_for(
            "dashboard.index",
            rtype=session[constants.TYPE_ARG],
            rstate=session[constants.RULE_ARG],
            sort=session[constants.SORT_ARG],
            squery=session[constants.SEARCH_ARG],
            order=session[constants.ORDER_ARG],
        )
    )


@rules.route("/delete_and_whitelist/<int:rule_type>/<int:rule_id>", methods=["GET"])
@auth_required
@user_or_admin_required
def delete_and_whitelist(rule_type, rule_id):
    """
    Delete an RTBH rule and create a whitelist entry from it.
    """
    # Validate CSRF token from query parameter
    try:
        validate_csrf(request.args.get("csrf_token", ""))
    except ValidationError:
        flash("CSRF token missing or invalid.", "alert-danger")
        return redirect(url_for("dashboard.index"))

    if rule_type != RuleTypes.RTBH.value:
        flash("Only RTBH rules can be converted to whitelists", "alert-warning")
        return redirect(url_for("index"))

    # Check if user can modify this rule
    if not check_user_can_modify_rule(rule_id, "rtbh"):
        flash("You cannot delete this rule", "alert-warning")
        return redirect(url_for("index"))

    # Get allowed rule IDs
    allowed_rule_ids = get_user_allowed_rule_ids("rtbh", session["user_id"], session["user_role_ids"])

    # Set whitelist expiration to 7 days from now by default
    whitelist_expires = datetime.now() + timedelta(days=7)

    # Use the service to delete RTBH and create whitelist
    success, messages, whitelist = rule_service.delete_rtbh_and_create_whitelist(
        rule_id=rule_id,
        user_id=session["user_id"],
        org_id=session["user_org_id"],
        user_email=session["user_email"],
        org_name=session["user_org"],
        allowed_rule_ids=allowed_rule_ids,
        whitelist_expires=whitelist_expires,
    )

    for message in messages:
        flash(message, "alert-success" if success else "alert-warning")

    if success and whitelist:
        flash(f"Created whitelist entry ID {whitelist.id} from RTBH rule", "alert-info")

    return redirect(
        url_for(
            "dashboard.index",
            rtype=session[constants.TYPE_ARG],
            rstate=session[constants.RULE_ARG],
            sort=session[constants.SORT_ARG],
            squery=session[constants.SEARCH_ARG],
            order=session[constants.ORDER_ARG],
        )
    )


@rules.route("/group-operation", methods=["POST"])
@auth_required
@user_or_admin_required
def group_operation():
    """
    Delete rules
    """
    dispatch = {"group-update": group_update, "group-delete": group_delete}

    try:
        return dispatch[request.form["action"]]()
    except KeyError:
        flash("Key Error in action dispatching!", "alert-danger")
        return redirect(
            url_for(
                "dashboard.index",
                rtype=session[constants.TYPE_ARG],
                rstate=session[constants.RULE_ARG],
                sort=session[constants.SORT_ARG],

flowapp/templates/macros.html
{% macro build_ip_tbody(rules, today, editable=True, group_op=True, whitelist_rule_ids=None, allowed_communities=None) %}
<tbody>
    {% for rule in rules %}
        {% if rule.next_header is defined %}
            {% set rtype_int = 6 %}
        {% else %}
            {% set rtype_int = 4 %}
        {% endif %}

        <tr 
        {% if rule.expires < today %} class="table-warning" 
        {% elif rule.rstate_id == 4 %} class="table-success" 
        {% elif whitelist_rule_ids and rule.id in whitelist_rule_ids %} class="table-secondary"
        {% endif %}>
            <td>
                <span class="task">{{ rule.source }}</span>{% if rule.source_mask != none %}{{ '/' if rule.source_mask >= 0 else '' }}{{ rule.source_mask if rule.source_mask >= 0 else '' }}{% endif %}
            </td>
            <td>
                {{ rule.source_port }}
            </td>
            <td>
                <span class="task">{{ rule.dest }}</span>{% if rule.dest_mask != none %}{{ '/' if rule.dest_mask >= 0 else '' }}{{ rule.dest_mask if rule.dest_mask >= 0 else '' }}{% endif %}
            </td>
            <td>
                {{ rule.dest_port }}
            </td>
            <td>
                {% if rtype_int == 4 %}
                    {{ rule.protocol }}
                {% elif rtype_int == 6 %}
                    {{ rule.next_header }}
                {% endif %}
            </td>
            <td>
                {{ rule.packet_len }}
            </td>
            <td>
                {{ rule.expires|strftime }}
            </td>
            <td>
                {{ rule.action.name }}
            </td>
            <td>
                {{ rule.flags}}
            </td>
            <td>
                {{ rule.user.name }}
            </td>
            <td>
            {% if editable %}
                <a class="btn btn-info btn-sm" href="{{ url_for('rules.reactivate_rule', rule_type=rtype_int, rule_id=rule.id) }}" role="button" data-bs-toggle="tooltip" data-bs-placement="top" title="set expiration">
                    <i class="bi bi-clock table-icon"></i>
                </a>
                <a class="btn btn-danger btn-sm" href="{{ url_for('rules.delete_rule', rule_type=rtype_int, rule_id=rule.id, csrf_token=csrf_token()) }}" role="button" data-bs-toggle="tooltip" data-bs-placement="top" title="delete" onclick="return confirm('Are you sure you want to delete this rule?');">
                    <i class="bi bi-x-lg"></i>
                </a>
            {% endif %}
            {% if rule.comment %}
                <button type="button" class="btn btn-info btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="{{ rule.comment }}">
                    <i class="bi bi-chat-left-text-fill"></i>
                </button>
            {% endif %}
            </td>

            {% if editable and group_op %}
                <td class="text-center">
                    <input type="checkbox" name="delete-id" value="{{rule.id}}" />
                </td>
            {% endif %}

        </tr>


    {% endfor %}
</tbody>
{% endmacro %}


{% macro build_rtbh_tbody(rules, today, editable=True, group_op=True, whitelist_rule_ids=None, allowed_communities=None) %}
    <tbody>
{% for rule in rules %}
    <tr 
    {% if rule.expires < today %} class="table-warning" 
    {% elif rule.rstate_id == 4 %} class="table-success" 
    {% elif whitelist_rule_ids and rule.id in whitelist_rule_ids %} class="table-secondary"
    {% endif %}>
        <td>
        {% if rule.ipv4 %}
            <span class="task">{{ rule.ipv4 }}</span>{{ '/' if rule.ipv4_mask else '' }}{{rule.ipv4_mask|default("", True)}}
        {% endif %}
        {% if rule.ipv6 %}
            <span class="task">{{ rule.ipv6 }}</span>{{ '/' if rule.ipv6_mask else '' }} {{rule.ipv6_mask|default("", True)}}
        {% endif %}
        </td>
        <td>
            {{ rule.community.name }}
        </td>

        <td>
            {{ rule.expires|strftime }}
        </td>
        <td>
            {{ rule.user.name }}
        </td>
        <td>
            {% if editable %}
                <a class="btn btn-info btn-sm" href="{{ url_for('rules.reactivate_rule', rule_type=1, rule_id=rule.id) }}" role="button" data-bs-toggle="tooltip" data-bs-placement="top" title="set expiration">
                    <i class="bi bi-clock table-icon"></i>
                </a>
                <a class="btn btn-danger btn-sm" href="{{ url_for('rules.delete_rule', rule_type=1, rule_id=rule.id, csrf_token=csrf_token()) }}" role="button" data-bs-toggle="tooltip" data-bs-placement="top" title="delete" onclick="return confirm('Are you sure you want to delete this rule?');">
                    <i class="bi bi-x-lg"></i>
                </a>
                {% if rule.community.id in allowed_communities %}
                    <a class="btn btn-success btn-sm" href="{{ url_for('rules.delete_and_whitelist', rule_type=1, rule_id=rule.id, csrf_token=csrf_token()) }}" role="button" data-bs-toggle="tooltip" data-bs-placement="top" title="whitelist and delete" onclick="return confirm('Are you sure you want to whitelist and delete this rule?');">
                        <i class="bi bi-shield-x"></i>
                    </a>
                {% endif %}
            {% endif %}
            {% if rule.comment %}
            <button type="button" class="btn btn-info btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="{{ rule.comment }}">
                <i class="bi bi-chat-left-text-fill"></i>
            </button>
            {% endif %}
        </td>
        {% if editable and group_op %}
                <td class="text-center">
                    <input type="checkbox" name="delete-id" value="{{rule.id}}" />
                </td>
        {% endif %}

    </tr>
{% endfor %}
</tbody>
{% endmacro %}


{% macro build_whitelist_tbody(rules, today, editable=True, group_op=True, whitelist_rule_ids=None, allowed_communities=None) %}
    <tbody>
{% for rule in rules %}
    <tr {% if rule.expires < today %} class="warning"  {% endif %}>
    <td>
        <span class="task">{{ rule.ip }}</span>{{ '/' if rule.mask else '' }}{{rule.mask|default("", True)}}
    </td>
    <td>
        {{ rule.expires|strftime }}
    </td>
    <td>
        {{ rule.user.name }}
    </td>
    <td>
        {% if editable %}
        <a class="btn btn-info btn-sm" href="{{ url_for('whitelist.reactivate', wl_id=rule.id) }}" role="button" data-bs-toggle="tooltip" data-bs-placement="top" title="set expiration">
            <i class="bi bi-clock table-icon"></i>
        </a>
        <a class="btn btn-danger btn-sm" href="{{ url_for('whitelist.delete', wl_id=rule.id, csrf_token=csrf_token()) }}" role="button" data-bs-toggle="tooltip" data-bs-placement="top" title="delete" onclick="return confirm('Are you sure you want to delete this whitelist?');">
            <i class="bi bi-x-lg"></i>
        </a>
        {% endif %}
        {% if rule.comment %}
           <button type="button" class="btn btn-info btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="{{ rule.comment }}">
              <i class="bi bi-chat-left-text-fill"></i>
           </button>
         {% endif %}
    </td>
     {% if editable and group_op %}
            <td class="text-center">
                <input type="checkbox" name="delete-id" value="{{rule.id}}" />
            </td>
    {% endif %}

    </tr>
{% endfor %}
</tbody>
{% endmacro %}



{% macro build_rules_thead(rules_columns, rtype, rstate, sort_key, sort_order, search_query='', group_op=True) %}
<thead>
    <tr class="table-sorter">
    {% for sort_key, col_name in rules_columns %}
    <th>
        {% if search_query %}
            <a href="{{ url_for('dashboard.index', rtype=rtype, rstate=rstate, sort=sort_key, order=sort_order, ordsrc='link', squery=search_query) }}" >
        {% else %}
            <a href="{{ url_for('dashboard.index', rtype=rtype, rstate=rstate, sort=sort_key, order=sort_order, ordsrc='link') }}" >
        {% endif %}
        {{ col_name }}
        </a>
        <span class="sort-direction {{ sort_order }}"></span>
    </th>
    {% endfor %}
    <th>Edit</th>
    {% if group_op %}
        <th class="text-center">
            <input id="check-all" type="checkbox">
        </th>
    {% endif %}
    </tr>
</thead>
{% endmacro %}

{% macro build_group_buttons_tfoot(button_colspan=10) %}
<tr>
    <td colspan="{{ button_colspan }}">
    </td>
    <td  class="text-center">

        <button type="submit" name="action" value="group-delete" class="btn btn-danger btn-sm" id="group-delete"  data-bs-toggle="tooltip" data-bs-placement="top" title="delete selected rules">
            <i class="bi bi-x-lg"></i>
        </button>

        <button type="submit" name="action" value="group-update" class="btn btn-primary btn-sm" id="group-update" data-bs-toggle="tooltip" data-bs-placement="top" title="update selected rules">
            <i class="bi bi-clock"></i>
        </button>
    </td>
</tr>
{% endmacro %}

flowapp/templates/macros.j2
{% macro build_ip_tbody(rules, today, editable=True, group_op=True) %}
<tbody>
    {% for rule in rules %}
        {% if rule.next_header is defined %}
            {% set rtype_int = 6 %}
        {% else %}
            {% set rtype_int = 4 %}
        {% endif %}

        <tr {% if rule.expires < today %} class="warning" {% endif %}>
            <td>
                <span class="task">{{ rule.source }}</span>{% if rule.source_mask != none %}{{ '/' if rule.source_mask >= 0 else '' }}{{ rule.source_mask if rule.source_mask >= 0 else '' }}{% endif %}
            </td>
            <td>
                {{ rule.source_port }}
            </td>
            <td>
                <span class="task">{{ rule.dest }}</span>{% if rule.dest_mask != none %}{{ '/' if rule.dest_mask >= 0 else '' }}{{ rule.dest_mask if rule.dest_mask >= 0 else '' }}{% endif %}
            </td>
            <td>
                {{ rule.dest_port }}
            </td>
            <td>
                {% if rtype_int == 4 %}
                    {{ rule.protocol }}
                {% elif rtype_int == 6 %}
                    {{ rule.next_header }}
                {% endif %}
            </td>
            <td>
                {{ rule.packet_len }}
            </td>
            <td>
                {{ rule.expires|strftime }}
            </td>
            <td>
                {{ rule.action.name }}
            </td>
            <td>
                {{ rule.flags}}
            </td>
            <td>
                {{ rule.user.name }}
            </td>
            <td>
            {% if editable %}
                <a class="btn btn-info btn-sm" href="{{ url_for('rules.reactivate_rule', rule_type=rtype_int, rule_id=rule.id) }}" role="button">
                    <i class="bi bi-clock table-icon"></i>
                </a>
                <a class="btn btn-danger btn-sm" href="{{ url_for('rules.delete_rule', rule_type=rtype_int, rule_id=rule.id) }}" role="button">
                    <i class="bi bi-x-lg"></i>
                </a>
            {% endif %}
            {% if rule.comment %}
                <button type="button" class="btn btn-info btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="{{ rule.comment }}">
                    <i class="bi bi-chat-left-text-fill"></i>
                </button>
            {% endif %}
            </td>

            {% if editable and group_op %}
                <td class="text-center">
                    <input type="checkbox" name="delete-id" value="{{rule.id}}" />
                </td>
            {% endif %}

        </tr>


    {% endfor %}
</tbody>
{% endmacro %}


{% macro build_rtbh_tbody(rules, today, editable=True, group_op=True) %}
    <tbody>
{% for rule in rules %}
    <tr {% if rule.expires < today %} class="warning"  {% endif %}>
    <td>
    {% if rule.ipv4 %}
        <span class="task">{{ rule.ipv4 }}</span>{{ '/' if rule.ipv4_mask else '' }}{{rule.ipv4_mask|default("", True)}}
    {% endif %}
    {% if rule.ipv6 %}
        <span class="task">{{ rule.ipv6 }}</span>{{ '/' if rule.ipv6_mask else '' }} {{rule.ipv6_mask|default("", True)}}
    {% endif %}
    </td>
     <td>
        {{ rule.community.name }}
    </td>

     <td>
        {{ rule.expires|strftime }}
    </td>
    <td>
        {{ rule.user.name }}
    </td>
    <td>
        {% if editable %}
        <a class="btn btn-info btn-sm" href="{{ url_for('rules.reactivate_rule', rule_type=1, rule_id=rule.id) }}" role="button">
            <i class="bi bi-clock table-icon"></i>
        </a>
        <a class="btn btn-danger btn-sm" href="{{ url_for('rules.delete_rule', rule_type=1, rule_id=rule.id) }}" role="button">
            <i class="bi bi-x-lg"></i>
        </a>
        {% endif %}
        {% if rule.comment %}
           <button type="button" class="btn btn-info btn-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="{{ rule.comment }}">
              <i class="bi bi-chat-left-text-fill"></i>
           </button>
         {% endif %}
    </td>
     {% if editable and group_op %}
            <td class="text-center">
                <input type="checkbox" name="delete-id" value="{{rule.id}}" />
            </td>
    {% endif %}

    </tr>
{% endfor %}
</tbody>
{% endmacro %}


{% macro build_rules_thead(rules_columns, rtype, rstate, sort_key, sort_order, search_query='', group_op=True) %}
<thead>
    <tr class="table-sorter">
    {% for sort_key, col_name in rules_columns %}
    <th>
        {% if search_query %}
            <a href="{{ url_for('dashboard.index', rtype=rtype, rstate=rstate, sort=sort_key, order=sort_order, ordsrc='link', squery=search_query) }}" >
        {% else %}
            <a href="{{ url_for('dashboard.index', rtype=rtype, rstate=rstate, sort=sort_key, order=sort_order, ordsrc='link') }}" >
        {% endif %}
        {{ col_name }}
        </a>
        <span class="sort-direction {{ sort_order }}"></span>
    </th>
    {% endfor %}
    <th>Edit</th>
    {% if group_op %}
        <th class="text-center">
            <input id="check-all" type="checkbox">
        </th>
    {% endif %}
    </tr>
</thead>
{% endmacro %}

{% macro build_group_buttons_tfoot(button_colspan=10) %}
<tr>
    <td colspan="{{ button_colspan }}">
    </td>
    <td  class="text-center">

        <button type="submit" name="action" value="group-delete" class="btn btn-danger btn-sm" id="group-delete"  data-bs-toggle="tooltip" data-bs-placement="top" title="delete selected rules">
            <i class="bi bi-x-lg"></i>
        </button>

        <button type="submit" name="action" value="group-update" class="btn btn-primary btn-sm" id="group-update" data-bs-toggle="tooltip" data-bs-placement="top" title="update selected rules">
            <i class="bi bi-clock"></i>
        </button>
    </td>
</tr>
{% endmacro %}